/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemstore;

/**
 *
 * @author LUIS FELIPE
 */
public class ADMINISTRADOR extends javax.swing.JFrame {

    /**
     * Creates new form ADMINISTRADOR
     */
    public ADMINISTRADOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INVENTARIO = new javax.swing.JButton();
        FACTURAR = new javax.swing.JButton();
        VENTAS = new javax.swing.JButton();
        GANANCIAS = new javax.swing.JButton();
        OPCIONES = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        VENDER = new javax.swing.JButton();
        FONDOADMIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        INVENTARIO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        INVENTARIO.setForeground(new java.awt.Color(255, 102, 0));
        INVENTARIO.setText("INVENTARIO");
        getContentPane().add(INVENTARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 190, 90));

        FACTURAR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FACTURAR.setForeground(new java.awt.Color(255, 102, 0));
        FACTURAR.setText("FACTURAR");
        getContentPane().add(FACTURAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 190, 90));

        VENTAS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VENTAS.setForeground(new java.awt.Color(255, 102, 0));
        VENTAS.setText("VENTAS REALIZADAS");
        getContentPane().add(VENTAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 190, 90));

        GANANCIAS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GANANCIAS.setForeground(new java.awt.Color(255, 102, 0));
        GANANCIAS.setText("GANANCIAS");
        getContentPane().add(GANANCIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 190, 90));

        OPCIONES.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OPCIONES.setForeground(new java.awt.Color(255, 102, 0));
        OPCIONES.setText("DESARROLLADORES");
        OPCIONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPCIONESActionPerformed(evt);
            }
        });
        getContentPane().add(OPCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 220, 90));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("SALIR");
        jButton7.setAutoscrolls(true);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        VENDER.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        VENDER.setForeground(new java.awt.Color(255, 102, 0));
        VENDER.setText("VENDER");
        getContentPane().add(VENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 90));

        FONDOADMIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemstore/IMAGENES/FONDO.jpg"))); // NOI18N
        getContentPane().add(FONDOADMIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 910, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPCIONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPCIONESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPCIONESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMINISTRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMINISTRADOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FACTURAR;
    private javax.swing.JLabel FONDOADMIN;
    private javax.swing.JButton GANANCIAS;
    private javax.swing.JButton INVENTARIO;
    private javax.swing.JButton OPCIONES;
    private javax.swing.JButton VENDER;
    private javax.swing.JButton VENTAS;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
