/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systemstore;

/**
 *
 * @author LUIS FELIPE
 */
public class OPTIONS extends javax.swing.JFrame {

    /**
     * Creates new form OPTIONS
     */
    public OPTIONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLE = new javax.swing.JLabel();
        NAME1 = new javax.swing.JLabel();
        NAME2 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TITLE.setText("DISEÑADO Y CREADO POR: ");
        getContentPane().add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        NAME1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NAME1.setForeground(new java.awt.Color(255, 255, 255));
        NAME1.setText("JELEY SARAHI TORRES ESCAREÑO");
        getContentPane().add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        NAME2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NAME2.setForeground(new java.awt.Color(255, 255, 255));
        NAME2.setText("LUIS FELIPE DE LA ROSA GARCIA");
        getContentPane().add(NAME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/systemstore/IMAGENES/pathogens-700x425.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 627, 411));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPTIONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel NAME1;
    private javax.swing.JLabel NAME2;
    private javax.swing.JLabel TITLE;
    // End of variables declaration//GEN-END:variables
}
